# Generated by Django 6.0.5 on 2026-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='MALE', max_length=6),
            preserve_default=False,
        ),
    ]
